TRUNCATE TABLE projects RESTART IDENTITY CASCADE;

INSERT INTO projects (title, problem, summary, tech, image_url, live_url, repo_url) VALUES
  ('ulolTris',
   'Arcade Players that casually or competitively want to practice Tetris and block-stacking with adjustable controls.',
   'A Tetr.io-inspired stacker with different game modes and different aesthetics. Comes with tunable configurations similar to Competitive Tetris to tweak your preferred DAS, ARR, soft drop speed, etc.',
   ARRAY['JavaScript', 'HTML Canvas', 'Web Audio API', 'esbuild'],
   'shots/uloltrisgame.jpg', '', 'https://github.com/JCDC0/ulolTris'),
  ('Neon-Roguelike',
   'A quick game that runs on a phone or browser with pleasing or chaotic elements of a topdown roguelite game featuring shapes and chaos.',
   'A top down 2D roguelike shooter on a neon platform where a player shoots down different types of enemies of different shapes, sizes, abilities, and speed. Made with Google AI Studio.',
   ARRAY ['React','TypeScript','Vite','HTML Canvas'],
   'shots/neon-roguelike2.jpg', '', 'https://github.com/JCDC0/Neon-Roguelike'),
  ('HandsFree',
   'People with motor disabilities who need to use their phone without touch input.',
   'My Capstone Thesis. A mobile application that allows you to control your phone with your voice, all without privacy issues and supports English, Tagalog, and Taglish using a fine-tuned Whisper-tiny model running on a mobile device. No Internet Connection or an LLM is needed.',
   ARRAY['Android Accessibility Services', 'Whisper (ONNX)', 'Kotlin', 'Speech Recognition'],
   'shots/handsfree2.jpg', '', ''),
  ('AIRP',
   'Roleplay apps or chatapps commonly restrict the user heavily with subscriptions, context that is lost due to limits, presenting a poor quality service with almost little control for users.',
   'A Flutter app that allows the user full control of their conversations and decorate their messaging style with a variety of settings and full control of their chat context and LLM responses. Utilizes v1 or v2 Character Cards, BYOK, streaming replies, full background and text design controls, import and export text, settings, presets, and so much more.',
   ARRAY['Flutter','Dart','LLM APIs(OpenAI, OpenRouter, ETC)'],
   'shots/airp-text.jpg', '', 'https://github.com/JCDC0/AIRP'),
  ('Catnip Cafe',
   'A cat cafe may require the need to integrate a system to seamlessly order online and allow customers to be welcomed, showcasing their cats, and how to contact or find the cafe itself.',
   'A WEBCS project of a responsive website designed from Figma. Built with HTML, CSS, and includes a Mobile Hamburger Menu and a restaurant menu. Includes a display for cat images, the menu, contact information, and the home screen.',
   ARRAY['HTML','CSS','JavaScript','Figma'],
   'shots/catnipcafe1.jpg', 'https://jcdc0.github.io/Catnip-Cafe/', 'https://github.com/JCDC0/Catnip-Cafe'),
  ('LowBeam',
   'The need to play a racing arcade game without the need of having expensive hardware and the need to download a game or install it on your computer.',
   'A racing ps1 arcade webgame built with Three.js and Javascript. The game features an open world with highways, cities, and low poly environments. It includes five low poly vehicles that can be driven, refuelled, repair, and face off heavy traffic, rivals and police.',
   ARRAY['Three.js','JavaScript','Web Audio API'],
   'shots/lowbeam1.jpg', '', 'https://github.com/JCDC0/Lowbeam');
